defmodule StoreWeb.Endpoint do
  @moduledoc false

  use Sentry.PlugCapture
  use Phoenix.Endpoint, otp_app: :store

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_secure Application.compile_env(:store, [StoreWeb.Endpoint, :session_secure], false)
  @session_options [
    store: :cookie,
    key: "_store_key",
    signing_salt: "AJ3cgUJW",
    same_site: "Lax",
    secure: @session_secure
  ]

  socket "/live", StoreWeb.LiveSocket,
    websocket: [connect_info: [:peer_data, :uri, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :uri, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :store,
    gzip: not code_reloading?,
    only: StoreWeb.static_paths(),
    cache_control_for_etags: "public, max-age=31536000, immutable",
    cache_control_for_vsn_requests: "public, max-age=31536000, immutable",
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :store
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug StoreWeb.Plugs.RemoteIp
  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]
  plug Sentry.PlugContext

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    body_reader: {StoreWeb.RawBodyReader, :read_body, []},
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug StoreWeb.Plugs.WaitingRoom
  plug StoreWeb.Router
end
