[
  {"lib/store/accounts/user/senders/send_new_user_confirmation_email.ex",
   :callback_type_mismatch},
  {"lib/store/accounts/user/senders/send_password_reset_email.ex", :callback_type_mismatch},
  {"lib/store/admin/changes/audit_after_action.ex", :guard_fail},
  {"lib/store/carts/facade.ex", :pattern_match_cov},
  {"lib/store/carts/inputs/cart_item_input.ex", :contract_supertype},
  {"lib/store/catalog/availability_cache.ex", :unmatched_return},
  {"lib/store/catalog/category.ex", :call_to_missing},
  {"lib/store/catalog/facade.ex", :pattern_match},
  {"lib/store/catalog/stock_fast_path.ex", :unmatched_return},
  {"lib/store/checkout/domain.ex", :guard_fail},
  {"lib/store/checkout/domain.ex", :unused_fun},
  {"lib/store/checkout/domain.ex", :pattern_match},
  {"lib/store/checkout/domain.ex", :pattern_match_cov},
  {"lib/store/comms/domain.ex", :extra_range},
  {"lib/store/comms/domain.ex", :pattern_match},
  {"lib/store/comms/domain.ex", :unused_fun},
  {"lib/store/comms/providers.ex", :contract_supertype},
  {"lib/store/digital/facade.ex", :pattern_match_cov},
  {"lib/store/digital/storage_providers.ex", :contract_supertype},
  {"lib/store/digital/storage_providers/ex_aws_s3_adapter.ex", :no_return},
  {"lib/store/digital/storage_providers/ex_aws_s3_adapter.ex", :call},
  {"lib/store/payments/domain.ex", :contract_supertype},
  {"lib/store/pricing/tax_shipping_evaluator.ex", :pattern_match},
  {"lib/store/repo.ex", :no_return},
  {"lib/store/support/errors/normalize.ex", :contract_supertype},
  {"lib/store/support/governance/idempotency.ex", :pattern_match_cov},
  {"lib/store/support/governance/surface_registry.ex", :invalid_contract},
  {"lib/store/support/id/prefixed_id.ex", :pattern_match_cov},
  {"lib/store/support/id/uuid_v7.ex", :contract_supertype},
  {"lib/store/support/rate_limit/ets_backend.ex", :unmatched_return},
  {"lib/store/workers/deliver_email_outbox_worker.ex", :pattern_match},
  {"lib/store_web/controllers/payment_callback_controller.ex", :pattern_match},
  {"lib/store_web/controllers/webhook_controller.ex", :pattern_match},
  {"lib/store_web/live/admin/email_outbox/index_live.ex", :guard_fail},
  {"test/support/subscriptions_fixtures.ex", :contract_supertype},
  {"test/support/test_fixtures.ex", :contract_supertype}
]
