import Config

# Configure your database
# 1. The High-Velocity Proxy Route (Hits PgBouncer)
config :store, Store.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 6432,
  database: "store_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 20,
  prepare: :unnamed

# 2. The Direct Route (Hits Postgres directly for Oban)
config :store, Store.DirectRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5433,
  database: "store_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 5

config :store,
       :token_signing_secret,
       System.get_env("STORE_TOKEN_SIGNING_SECRET", "dev-store-token-signing-secret")

config :store, :google_oauth,
  client_id: System.get_env("STORE_GOOGLE_CLIENT_ID", "dev-google-client-id"),
  client_secret: System.get_env("STORE_GOOGLE_CLIENT_SECRET", "dev-google-client-secret"),
  redirect_uri_base:
    System.get_env("STORE_GOOGLE_REDIRECT_URI_BASE", "http://localhost:4000/auth")

config :store, :payments,
  enabled_providers: [:stripe],
  default_purchase_provider_for_ui: :stripe,
  stripe: [
    webhook_secret: System.get_env("STORE_STRIPE_WEBHOOK_SECRET", "whsec_dev_only_change_me")
  ]

config :store, :shipping,
  quote_hash_secret: System.get_env("STORE_QUOTE_HASH_SECRET", "phase22-dev-only-change-me")

rate_limit_backend =
  case System.get_env("STORE_RATE_LIMIT_BACKEND", "redis") do
    "ets" -> Store.Support.RateLimit.EtsBackend
    "redis" -> Store.Support.RateLimit.RedisBackend
    value -> raise "invalid STORE_RATE_LIMIT_BACKEND value: #{value}"
  end

redis_tls? = System.get_env("STORE_REDIS_SSL", "false") in ~w(true 1)

config :store, :rate_limit,
  backend: rate_limit_backend,
  redis_client: Store.Support.RateLimit.RedixClient,
  redis_name: :store_rate_limit_redis,
  redis_key_prefix: System.get_env("STORE_REDIS_KEY_PREFIX", "dev:store"),
  # For host-based dev with Docker Redis, publish the container port (e.g. -p 6379:6379).
  redis: [
    host: System.get_env("STORE_REDIS_HOST", "localhost"),
    port: String.to_integer(System.get_env("STORE_REDIS_PORT", "6379")),
    database: String.to_integer(System.get_env("STORE_REDIS_DB", "0")),
    username: System.get_env("STORE_REDIS_USERNAME"),
    password: System.get_env("STORE_REDIS_PASSWORD"),
    ssl: redis_tls?
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :store, StoreWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "k2xuHZUMMu79bkGU7M1GtnmyOFS5zVXVY2MpYX4OlKCIisLyJUFiQ5gXO3CQGgfB",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:store, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:store, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :store, StoreWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/store_web/router\.ex$"E,
      ~r"lib/store_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :store, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

if System.get_env("STORE_DEV_SMTP_ENABLED") == "true" do
  config :store, Store.Mailer,
    adapter: Swoosh.Adapters.SMTP,
    relay: System.get_env("STORE_SMTP_HOST", "localhost"),
    port: String.to_integer(System.get_env("STORE_SMTP_PORT", "1025")),
    username: System.get_env("STORE_SMTP_USERNAME"),
    password: System.get_env("STORE_SMTP_PASSWORD"),
    tls: :if_available,
    auth: :if_available
end

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
