PROJECT_KEY=store_blueprint
DEV_DB_ROLE=store_blueprint_dev
DEV_DB_NAME=store_blueprint_dev
TEST_DB_ROLE=store_blueprint_test
TEST_DB_NAME=store_blueprint_test
DEV_SECRET_KEY=STORE_BLUEPRINT_DEV_DB_PASSWORD
TEST_SECRET_KEY=STORE_BLUEPRINT_TEST_DB_PASSWORD
TEST_ROLE_CREATEDB=yes
USE_REDIS=yes
REDIS_PREFIX=store_blueprint_hardening
RENDER_MAP=.devcore/render-map.tsv
