defmodule Store.Repo.Migrations.Sbh1006ContractChangeFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contract_changes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false, default: "queued"
      add :instruction_kind, :text, null: false
      add :ordering_version, :bigint, null: false
      add :effective_at, :utc_datetime_usec, null: false
      add :target_quantity, :bigint, null: false
      add :target_amount_minor, :bigint, null: false
      add :target_currency, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscription_id,
          references(:subscriptions,
            column: :id,
            name: "contract_changes_subscription_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :target_plan_revision_id,
          references(:plan_revisions,
            column: :id,
            name: "contract_changes_target_plan_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :target_variant_id,
          references(:variants,
            column: :id,
            name: "contract_changes_target_variant_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :predecessor_contract_change_id,
          references(:contract_changes,
            column: :id,
            name: "contract_changes_predecessor_contract_change_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :supersedes_contract_change_id,
          references(:contract_changes,
            column: :id,
            name: "contract_changes_supersedes_contract_change_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:contract_changes, :contract_changes_status_value_check,
             check: """
               status IN ('queued', 'superseded', 'canceled', 'bound_to_renewal', 'applied')
             """
           )

    create constraint(:contract_changes, :contract_changes_instruction_kind_value_check,
             check: """
               instruction_kind IN ('plan_change', 'variant_change', 'renew_unchanged')
             """
           )

    create constraint(:contract_changes, :contract_changes_ordering_version_check,
             check: """
               ordering_version >= 1
             """
           )

    create constraint(:contract_changes, :contract_changes_target_quantity_check,
             check: """
               target_quantity >= 1
             """
           )

    create constraint(:contract_changes, :contract_changes_target_amount_minor_check,
             check: """
               target_amount_minor >= 0
             """
           )

    create constraint(:contract_changes, :contract_changes_target_currency_check,
             check: """
               length(target_currency) = 3 AND target_currency = upper(target_currency)
             """
           )

    create index(:contract_changes, [:subscription_id],
             name: "contract_changes_subscription_id_index"
           )

    create index(:contract_changes, [:subscription_id, :ordering_version],
             name: "contract_changes_subscription_ordering_version_index",
             unique: true
           )

    create index(:contract_changes, [:subscription_id],
             name: "contract_changes_one_queued_per_subscription_index",
             unique: true,
             where: "status = 'queued'"
           )

    create index(:contract_changes, [:target_plan_revision_id],
             name: "contract_changes_target_plan_revision_id_index"
           )

    create index(:contract_changes, [:target_variant_id],
             name: "contract_changes_target_variant_id_index"
           )

    create index(:contract_changes, [:predecessor_contract_change_id],
             name: "contract_changes_predecessor_id_index"
           )

    create index(:contract_changes, [:supersedes_contract_change_id],
             name: "contract_changes_supersedes_id_index"
           )

    alter table(:subscriptions) do
      add :current_contract_change_id,
          references(:contract_changes,
            column: :id,
            name: "subscriptions_current_contract_change_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create index(:subscriptions, [:current_contract_change_id],
             name: "subscriptions_current_contract_change_id_index"
           )
  end

  def down do
    drop_if_exists index(:subscriptions, [:current_contract_change_id],
                     name: "subscriptions_current_contract_change_id_index"
                   )

    drop constraint(:subscriptions, "subscriptions_current_contract_change_id_fkey")

    alter table(:subscriptions) do
      remove :current_contract_change_id
    end

    drop_if_exists index(:contract_changes, [:supersedes_contract_change_id],
                     name: "contract_changes_supersedes_id_index"
                   )

    drop_if_exists index(:contract_changes, [:predecessor_contract_change_id],
                     name: "contract_changes_predecessor_id_index"
                   )

    drop_if_exists index(:contract_changes, [:target_variant_id],
                     name: "contract_changes_target_variant_id_index"
                   )

    drop_if_exists index(:contract_changes, [:target_plan_revision_id],
                     name: "contract_changes_target_plan_revision_id_index"
                   )

    drop_if_exists index(:contract_changes, [:subscription_id],
                     name: "contract_changes_one_queued_per_subscription_index"
                   )

    drop_if_exists index(:contract_changes, [:subscription_id, :ordering_version],
                     name: "contract_changes_subscription_ordering_version_index"
                   )

    drop_if_exists index(:contract_changes, [:subscription_id],
                     name: "contract_changes_subscription_id_index"
                   )

    drop_if_exists constraint(:contract_changes, :contract_changes_target_currency_check)

    drop_if_exists constraint(:contract_changes, :contract_changes_target_amount_minor_check)

    drop_if_exists constraint(:contract_changes, :contract_changes_target_quantity_check)

    drop_if_exists constraint(:contract_changes, :contract_changes_ordering_version_check)

    drop_if_exists constraint(:contract_changes, :contract_changes_instruction_kind_value_check)

    drop_if_exists constraint(:contract_changes, :contract_changes_status_value_check)

    drop constraint(:contract_changes, "contract_changes_supersedes_contract_change_id_fkey")

    drop constraint(:contract_changes, "contract_changes_predecessor_contract_change_id_fkey")

    drop constraint(:contract_changes, "contract_changes_target_variant_id_fkey")

    drop constraint(:contract_changes, "contract_changes_target_plan_revision_id_fkey")

    drop constraint(:contract_changes, "contract_changes_subscription_id_fkey")

    drop table(:contract_changes)
  end
end
