defmodule Store.Repo.Migrations.DepSec03UserIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_identities, primary_key: false) do
      add :strategy, :text, null: false
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :uid, :text, null: false
      add :access_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :refresh_token, :text

      add :user_id,
          references(:users,
            column: :id,
            name: "user_identities_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )
  end

  def down do
    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    drop constraint(:user_identities, "user_identities_user_id_fkey")

    drop table(:user_identities)
  end
end
