defmodule Store.Repo.Migrations.Sbh1002SubscriptionCurrentRevision do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions) do
      add :current_plan_revision_id,
          references(:plan_revisions,
            column: :id,
            name: "subscriptions_current_plan_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create index(:subscriptions, [:current_plan_revision_id],
             name: "subscriptions_current_plan_revision_id_index"
           )
  end

  def down do
    drop_if_exists index(:subscriptions, [:current_plan_revision_id],
                     name: "subscriptions_current_plan_revision_id_index"
                   )

    drop constraint(:subscriptions, "subscriptions_current_plan_revision_id_fkey")

    alter table(:subscriptions) do
      remove :current_plan_revision_id
    end
  end
end
