defmodule Store.Repo.Migrations.Sbh1001PlanRevisionFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:plan_revisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false, default: "draft"
      add :version, :bigint, null: false, default: 1
      add :interval_unit, :text, null: false, default: "month"
      add :interval_count, :bigint, null: false, default: 1
      add :currency, :text, null: false, default: "USD"
      add :amount_minor, :bigint, null: false
      add :trial_days, :bigint
      add :anchor_mode, :text, null: false, default: "start_anniversary"
      add :anchor_day_of_month, :bigint
      add :billing_timezone, :text, null: false, default: "Africa/Johannesburg"
      add :term_mode, :text, null: false, default: "until_canceled"
      add :term_cycles, :bigint
      add :term_end_at, :utc_datetime_usec
      add :access_on_past_due, :text, null: false, default: "keep_during_grace"
      add :access_on_cancel, :text, null: false, default: "keep_until_period_end"
      add :grace_period_days, :bigint, null: false, default: 7
      add :max_retry_attempts, :bigint, null: false, default: 3
      add :retry_schedule_hours, {:array, :bigint}, null: false, default: [0, 24, 72]
      add :entitlement_kind, :text
      add :entitlement_scope_key, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscription_plan_id,
          references(:subscription_plans,
            column: :id,
            name: "plan_revisions_subscription_plan_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create constraint(:plan_revisions, :plan_revisions_status_value_check,
             check: """
               status IN ('draft', 'effective', 'retired')
             """
           )

    create constraint(:plan_revisions, :plan_revisions_version_check,
             check: """
               version >= 1
             """
           )

    create constraint(:plan_revisions, :plan_revisions_interval_unit_value_check,
             check: """
               interval_unit IN ('day', 'month', 'year')
             """
           )

    create constraint(:plan_revisions, :plan_revisions_interval_count_check,
             check: """
               interval_count >= 1
             """
           )

    create constraint(:plan_revisions, :plan_revisions_amount_minor_non_negative_check,
             check: """
               amount_minor >= 0
             """
           )

    create constraint(:plan_revisions, :plan_revisions_trial_days_non_negative_check,
             check: """
               trial_days IS NULL OR trial_days >= 0
             """
           )

    create constraint(:plan_revisions, :plan_revisions_anchor_mode_value_check,
             check: """
               anchor_mode IN ('start_anniversary', 'fixed_day_of_month')
             """
           )

    create constraint(:plan_revisions, :plan_revisions_anchor_day_requirement_check,
             check: """
               (anchor_mode <> 'fixed_day_of_month') OR (anchor_day_of_month >= 1 AND anchor_day_of_month <= 31)
             """
           )

    create constraint(:plan_revisions, :plan_revisions_term_mode_value_check,
             check: """
               term_mode IN ('until_canceled', 'fixed_cycles', 'fixed_end_at')
             """
           )

    create constraint(:plan_revisions, :plan_revisions_term_cycles_requirement_check,
             check: """
               (term_mode <> 'fixed_cycles') OR (term_cycles IS NOT NULL AND term_cycles >= 1)
             """
           )

    create constraint(:plan_revisions, :plan_revisions_term_end_requirement_check,
             check: """
               (term_mode <> 'fixed_end_at') OR (term_end_at IS NOT NULL)
             """
           )

    create constraint(:plan_revisions, :plan_revisions_access_on_past_due_value_check,
             check: """
               access_on_past_due IN ('keep_during_grace', 'remove_immediately')
             """
           )

    create constraint(:plan_revisions, :plan_revisions_access_on_cancel_value_check,
             check: """
               access_on_cancel IN ('keep_until_period_end', 'remove_immediately')
             """
           )

    create constraint(:plan_revisions, :plan_revisions_grace_period_days_check,
             check: """
               grace_period_days >= 0
             """
           )

    create constraint(:plan_revisions, :plan_revisions_max_retry_attempts_check,
             check: """
               max_retry_attempts >= 0
             """
           )

    create index(:plan_revisions, [:subscription_plan_id],
             name: "plan_revisions_subscription_plan_id_index"
           )
  end

  def down do
    drop_if_exists index(:plan_revisions, [:subscription_plan_id],
                     name: "plan_revisions_subscription_plan_id_index"
                   )

    drop_if_exists constraint(:plan_revisions, :plan_revisions_max_retry_attempts_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_grace_period_days_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_access_on_cancel_value_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_access_on_past_due_value_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_term_end_requirement_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_term_cycles_requirement_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_term_mode_value_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_anchor_day_requirement_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_anchor_mode_value_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_trial_days_non_negative_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_amount_minor_non_negative_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_interval_count_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_interval_unit_value_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_version_check)

    drop_if_exists constraint(:plan_revisions, :plan_revisions_status_value_check)

    drop constraint(:plan_revisions, "plan_revisions_subscription_plan_id_fkey")

    drop table(:plan_revisions)
  end
end
