defmodule Store.Repo.Migrations.Sbh1003RenewalContractSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:renewal_attempts) do
      add :plan_revision_id,
          references(:plan_revisions,
            column: :id,
            name: "renewal_attempts_plan_revision_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :variant_id, :uuid
      add :quantity, :bigint
      add :amount_minor, :bigint
      add :currency, :text

      add :contract_change_id,
          references(:contract_changes,
            column: :id,
            name: "renewal_attempts_contract_change_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :expected_subscription_version, :bigint
      add :charged_contract_version, :bigint
      add :charged_contract_snapshot, :map
    end

    create constraint(:renewal_attempts, :renewal_attempts_charged_contract_completeness_check,
             check: """
                 (
                 charged_contract_version IS NULL
                 AND plan_revision_id IS NULL
                 AND variant_id IS NULL
                 AND quantity IS NULL
                 AND amount_minor IS NULL
                 AND currency IS NULL
                 AND contract_change_id IS NULL
                 AND expected_subscription_version IS NULL
                 AND charged_contract_snapshot IS NULL
               ) OR (
                 charged_contract_version = 1
                 AND plan_revision_id IS NOT NULL
                 AND variant_id IS NOT NULL
                 AND quantity IS NOT NULL AND quantity > 0
                 AND amount_minor IS NOT NULL AND amount_minor >= 0
                 AND currency IS NOT NULL AND currency ~ '^[A-Z]{3}$'
                 AND expected_subscription_version IS NOT NULL
                   AND expected_subscription_version > 0
                 AND charged_contract_snapshot IS NOT NULL
                   AND jsonb_typeof(charged_contract_snapshot) = 'object'
                   AND charged_contract_snapshot ?& ARRAY[
                     'version', 'subscription_plan_key',
                     'interval_unit', 'interval_count', 'trial_days', 'anchor_mode',
                     'anchor_day_of_month', 'billing_timezone', 'term_mode', 'term_cycles',
                     'term_end_at', 'access_on_past_due', 'access_on_cancel',
                     'grace_period_days', 'max_retry_attempts', 'retry_schedule_hours',
                     'entitlement_kind', 'entitlement_scope_key'
                   ]
                   AND jsonb_typeof(charged_contract_snapshot->'version') = 'number'
                   AND charged_contract_snapshot->>'version' = '1'
                   AND jsonb_typeof(charged_contract_snapshot->'subscription_plan_key') = 'string'
                   AND jsonb_typeof(charged_contract_snapshot->'interval_unit') = 'string'
                   AND charged_contract_snapshot->>'interval_unit' IN ('day', 'month', 'year')
                   AND jsonb_typeof(charged_contract_snapshot->'interval_count') = 'number'
                   AND (charged_contract_snapshot->>'interval_count')::numeric > 0
                   AND (charged_contract_snapshot->>'interval_count')::numeric =
                     trunc((charged_contract_snapshot->>'interval_count')::numeric)
                   AND (
                     jsonb_typeof(charged_contract_snapshot->'trial_days') = 'null'
                     OR (
                       jsonb_typeof(charged_contract_snapshot->'trial_days') = 'number'
                       AND (charged_contract_snapshot->>'trial_days')::numeric >= 0
                       AND (charged_contract_snapshot->>'trial_days')::numeric =
                         trunc((charged_contract_snapshot->>'trial_days')::numeric)
                     )
                   )
                   AND jsonb_typeof(charged_contract_snapshot->'anchor_mode') = 'string'
                   AND charged_contract_snapshot->>'anchor_mode'
                     IN ('start_anniversary', 'fixed_day_of_month')
                   AND jsonb_typeof(charged_contract_snapshot->'billing_timezone') = 'string'
                   AND charged_contract_snapshot->>'billing_timezone' <> ''
                   AND jsonb_typeof(charged_contract_snapshot->'term_mode') = 'string'
                   AND charged_contract_snapshot->>'term_mode'
                     IN ('until_canceled', 'fixed_cycles', 'fixed_end_at')
                   AND (
                     jsonb_typeof(charged_contract_snapshot->'anchor_day_of_month') = 'null'
                     OR (
                       jsonb_typeof(charged_contract_snapshot->'anchor_day_of_month') = 'number'
                       AND (charged_contract_snapshot->>'anchor_day_of_month')::numeric BETWEEN 1 AND 31
                       AND (charged_contract_snapshot->>'anchor_day_of_month')::numeric =
                         trunc((charged_contract_snapshot->>'anchor_day_of_month')::numeric)
                     )
                   )
                   AND (
                     jsonb_typeof(charged_contract_snapshot->'term_cycles') = 'null'
                     OR (
                       jsonb_typeof(charged_contract_snapshot->'term_cycles') = 'number'
                       AND (charged_contract_snapshot->>'term_cycles')::numeric > 0
                       AND (charged_contract_snapshot->>'term_cycles')::numeric =
                         trunc((charged_contract_snapshot->>'term_cycles')::numeric)
                     )
                   )
                   AND (
                     jsonb_typeof(charged_contract_snapshot->'term_end_at') = 'null'
                     OR jsonb_typeof(charged_contract_snapshot->'term_end_at') = 'string'
                   )
                   AND (
                     charged_contract_snapshot->>'term_mode' <> 'fixed_cycles'
                     OR jsonb_typeof(charged_contract_snapshot->'term_cycles') = 'number'
                   )
                   AND (
                     charged_contract_snapshot->>'term_mode' <> 'fixed_end_at'
                     OR jsonb_typeof(charged_contract_snapshot->'term_end_at') = 'string'
                   )
                   AND jsonb_typeof(charged_contract_snapshot->'access_on_past_due') = 'string'
                   AND charged_contract_snapshot->>'access_on_past_due'
                     IN ('keep_during_grace', 'remove_immediately')
                   AND jsonb_typeof(charged_contract_snapshot->'access_on_cancel') = 'string'
                   AND charged_contract_snapshot->>'access_on_cancel'
                     IN ('keep_until_period_end', 'remove_immediately')
                   AND jsonb_typeof(charged_contract_snapshot->'grace_period_days') = 'number'
                   AND (charged_contract_snapshot->>'grace_period_days')::numeric >= 0
                   AND (charged_contract_snapshot->>'grace_period_days')::numeric =
                     trunc((charged_contract_snapshot->>'grace_period_days')::numeric)
                   AND jsonb_typeof(charged_contract_snapshot->'max_retry_attempts') = 'number'
                   AND (charged_contract_snapshot->>'max_retry_attempts')::numeric >= 0
                   AND (charged_contract_snapshot->>'max_retry_attempts')::numeric =
                     trunc((charged_contract_snapshot->>'max_retry_attempts')::numeric)
                   AND jsonb_typeof(charged_contract_snapshot->'retry_schedule_hours') = 'array'
                   AND NOT jsonb_path_exists(
                     charged_contract_snapshot,
                     '$.retry_schedule_hours[*] ? (@.type() != "number" || @ < 0 || @ != @.floor())'
                   )
                   AND (
                     charged_contract_snapshot->'entitlement_kind' = 'null'::jsonb
                     OR charged_contract_snapshot->>'entitlement_kind'
                       IN ('membership_access', 'digital_library', 'discount_tier')
                   )
                   AND (
                     charged_contract_snapshot->'entitlement_scope_key' = 'null'::jsonb
                     OR jsonb_typeof(charged_contract_snapshot->'entitlement_scope_key') = 'string'
                   )
               )

             """
           )
  end

  def down do
    drop_if_exists constraint(
                     :renewal_attempts,
                     :renewal_attempts_charged_contract_completeness_check
                   )

    drop constraint(:renewal_attempts, "renewal_attempts_contract_change_id_fkey")

    drop constraint(:renewal_attempts, "renewal_attempts_plan_revision_id_fkey")

    alter table(:renewal_attempts) do
      remove :charged_contract_snapshot
      remove :charged_contract_version
      remove :expected_subscription_version
      remove :contract_change_id
      remove :currency
      remove :amount_minor
      remove :quantity
      remove :variant_id
      remove :plan_revision_id
    end
  end
end
