defmodule Store.Repo.Migrations.SyncCodegenBaseline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    :ok
  end

  def down do
    :ok
  end
end
