defmodule Store.Repo.Migrations.Sbh6001PlanRevisionEffectiveUniqueness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:plan_revisions, [:subscription_plan_id],
             name: "plan_revisions_one_effective_per_plan_index",
             unique: true,
             where: "status = 'effective'"
           )
  end

  def down do
    drop_if_exists index(:plan_revisions, [:subscription_plan_id],
                     name: "plan_revisions_one_effective_per_plan_index"
                   )
  end
end
