defmodule Store.Repo.Migrations.Phase04StateMachines do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:provider_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider, :text, null: false
      add :provider_event_id, :text, null: false
      add :provider_event_key, :text, null: false
      add :event_type, :text, null: false
      add :payload_sha256, :text
      add :payload_hash, :text

      add :received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:provider_events, [:received_at], name: "provider_events_received_at_index")

    create index(:provider_events, [:provider_event_key],
             name: "provider_events_provider_event_key_index"
           )

    create unique_index(:provider_events, [:provider, :provider_event_id],
             name: "provider_events_unique_provider_event_index"
           )

    create table(:payment_intents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :order_id, :uuid
      add :state, :text, null: false, default: "created"
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:payment_intents, [:order_id], name: "payment_intents_order_id_index")

    create index(:payment_intents, [:state], name: "payment_intents_state_index")

    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :state, :text, null: false, default: "pending_payment"
      add :version, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:orders, [:state], name: "orders_state_index")
  end

  def down do
    drop_if_exists index(:orders, [:state], name: "orders_state_index")

    drop table(:orders)

    drop_if_exists index(:payment_intents, [:state], name: "payment_intents_state_index")

    drop_if_exists index(:payment_intents, [:order_id], name: "payment_intents_order_id_index")

    drop table(:payment_intents)

    drop_if_exists unique_index(:provider_events, [:provider, :provider_event_id],
                     name: "provider_events_unique_provider_event_index"
                   )

    drop_if_exists index(:provider_events, [:provider_event_key],
                     name: "provider_events_provider_event_key_index"
                   )

    drop_if_exists index(:provider_events, [:received_at],
                     name: "provider_events_received_at_index"
                   )

    drop table(:provider_events)
  end
end
