defmodule Store.Repo.Migrations.Sbh1002OrderLineItemRevisionSnapshot do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:order_line_items) do
      add :subscription_plan_revision_id_snapshot,
          references(:plan_revisions,
            column: :id,
            name: "order_line_items_subscription_plan_revision_id_snapshot_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create index(:order_line_items, [:subscription_plan_revision_id_snapshot],
             name: "order_line_items_subscription_plan_revision_id_snapshot_index"
           )
  end

  def down do
    drop_if_exists index(:order_line_items, [:subscription_plan_revision_id_snapshot],
                     name: "order_line_items_subscription_plan_revision_id_snapshot_index"
                   )

    drop constraint(
           :order_line_items,
           "order_line_items_subscription_plan_revision_id_snapshot_fkey"
         )

    alter table(:order_line_items) do
      remove :subscription_plan_revision_id_snapshot
    end
  end
end
