defmodule Store.Repo.Migrations.Sbh2001SubscriptionOptimisticVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:subscriptions) do
      add :aggregate_version, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:subscriptions) do
      remove :aggregate_version
    end
  end
end
