defmodule Store.Repo.Migrations.Sbh5006AccessEffectFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:access_effects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :status, :text, null: false, default: "required"
      add :source_version, :bigint, null: false
      add :disposition, :text, null: false
      add :entitlement_kind, :text
      add :entitlement_scope_key, :text
      add :valid_until_at, :utc_datetime_usec
      add :target_fingerprint, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscription_id,
          references(:subscriptions,
            column: :id,
            name: "access_effects_subscription_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:access_effects, [:subscription_id, :source_version],
             name: "access_effects_unique_subscription_source_version_index"
           )

    alter table(:access_effects) do
      add :source_order_line_item_id,
          references(:order_line_items,
            column: :id,
            name: "access_effects_source_order_line_item_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :contract_change_id,
          references(:contract_changes,
            column: :id,
            name: "access_effects_contract_change_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :plan_revision_id,
          references(:plan_revisions,
            column: :id,
            name: "access_effects_plan_revision_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create constraint(:access_effects, :access_effects_status_value_check,
             check: """
               status IN ('required', 'pending', 'applied', 'failed_retryable', 'superseded')
             """
           )

    create constraint(:access_effects, :access_effects_source_version_check,
             check: """
               source_version >= 1
             """
           )

    create constraint(:access_effects, :access_effects_disposition_value_check,
             check: """
               disposition IN ('effective', 'non_effective')
             """
           )

    create constraint(:access_effects, :access_effects_entitlement_pair_complete_check,
             check: """
               (entitlement_kind IS NULL AND entitlement_scope_key IS NULL) OR
               (entitlement_kind IS NOT NULL AND entitlement_scope_key IS NOT NULL)
             """
           )

    create constraint(:access_effects, :access_effects_fingerprint_length_check,
             check: """
               length(target_fingerprint) = 64
             """
           )
  end

  def down do
    drop_if_exists constraint(:access_effects, :access_effects_fingerprint_length_check)

    drop_if_exists constraint(:access_effects, :access_effects_entitlement_pair_complete_check)

    drop_if_exists constraint(:access_effects, :access_effects_disposition_value_check)

    drop_if_exists constraint(:access_effects, :access_effects_source_version_check)

    drop_if_exists constraint(:access_effects, :access_effects_status_value_check)

    drop constraint(:access_effects, "access_effects_plan_revision_id_fkey")

    drop constraint(:access_effects, "access_effects_contract_change_id_fkey")

    drop constraint(:access_effects, "access_effects_source_order_line_item_id_fkey")

    drop constraint(:access_effects, "access_effects_subscription_id_fkey")

    alter table(:access_effects) do
      remove :plan_revision_id
      remove :contract_change_id
      remove :source_order_line_item_id
    end

    drop_if_exists unique_index(:access_effects, [:subscription_id, :source_version],
                     name: "access_effects_unique_subscription_source_version_index"
                   )

    drop table(:access_effects)
  end
end
