defmodule Store.Repo.Migrations.Sbh1004RenewalCollectionAttempts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:renewal_collection_attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :collection_ordinal, :bigint, null: false
      add :dispatch_state, :text, null: false, default: "not_started"
      add :financial_outcome, :text, null: false, default: "unresolved"
      add :reservation_generation_id, :uuid
      add :dispatch_epoch, :bigint, null: false, default: 1
      add :fenced_through_epoch, :bigint, null: false, default: 0
      add :last_fence_event_id, :uuid
      add :last_fenced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :renewal_attempt_id,
          references(:renewal_attempts,
            column: :id,
            name: "renewal_collection_attempts_renewal_attempt_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :payment_intent_id,
          references(:payment_intents,
            column: :id,
            name: "renewal_collection_attempts_payment_intent_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(
             :renewal_collection_attempts,
             :renewal_collection_attempts_dispatch_state_check,
             check: """
               dispatch_state IN ('not_started', 'may_have_been_reached', 'not_submitted')
             """
           )

    create constraint(
             :renewal_collection_attempts,
             :renewal_collection_attempts_financial_outcome_check,
             check: """
               financial_outcome IN ('unresolved', 'requires_action', 'verified_success', 'verified_terminal_financial_non_success')
             """
           )

    create constraint(
             :renewal_collection_attempts,
             :renewal_collection_attempts_collection_ordinal_positive_check,
             check: """
               collection_ordinal > 0
             """
           )

    create constraint(
             :renewal_collection_attempts,
             :renewal_collection_attempts_epoch_evidence_check,
             check: """
               dispatch_epoch > 0
             AND fenced_through_epoch >= 0
             AND fenced_through_epoch <= dispatch_epoch
             AND (
               (dispatch_state = 'not_submitted' AND fenced_through_epoch = dispatch_epoch)
               OR
               (dispatch_state <> 'not_submitted' AND fenced_through_epoch + 1 = dispatch_epoch)
             )
             AND (
               (fenced_through_epoch = 0 AND last_fence_event_id IS NULL AND last_fenced_at IS NULL)
               OR
               (fenced_through_epoch > 0 AND last_fence_event_id IS NOT NULL AND last_fenced_at IS NOT NULL)
             )
             AND (
               (dispatch_state = 'may_have_been_reached')
               OR
               (dispatch_state IN ('not_started', 'not_submitted') AND financial_outcome = 'unresolved')
             )

             """
           )

    create constraint(
             :renewal_collection_attempts,
             :renewal_collection_attempts_outcome_payment_intent_check,
             check: """
               financial_outcome = 'unresolved' OR payment_intent_id IS NOT NULL
             """
           )

    create index(:renewal_collection_attempts, [:renewal_attempt_id, :collection_ordinal],
             name: "renewal_collection_attempts_attempt_ordinal_index",
             unique: true
           )

    create index(:renewal_collection_attempts, [:renewal_attempt_id],
             name: "renewal_collection_attempts_one_active_index",
             unique: true,
             where: "financial_outcome IN ('unresolved', 'requires_action')"
           )

    create index(:renewal_collection_attempts, [:payment_intent_id],
             name: "renewal_collection_attempts_payment_intent_index",
             unique: true,
             where: "payment_intent_id IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:renewal_collection_attempts, [:payment_intent_id],
                     name: "renewal_collection_attempts_payment_intent_index"
                   )

    drop_if_exists index(:renewal_collection_attempts, [:renewal_attempt_id],
                     name: "renewal_collection_attempts_one_active_index"
                   )

    drop_if_exists index(:renewal_collection_attempts, [:renewal_attempt_id, :collection_ordinal],
                     name: "renewal_collection_attempts_attempt_ordinal_index"
                   )

    drop_if_exists constraint(
                     :renewal_collection_attempts,
                     :renewal_collection_attempts_outcome_payment_intent_check
                   )

    drop_if_exists constraint(
                     :renewal_collection_attempts,
                     :renewal_collection_attempts_epoch_evidence_check
                   )

    drop_if_exists constraint(
                     :renewal_collection_attempts,
                     :renewal_collection_attempts_collection_ordinal_positive_check
                   )

    drop_if_exists constraint(
                     :renewal_collection_attempts,
                     :renewal_collection_attempts_financial_outcome_check
                   )

    drop_if_exists constraint(
                     :renewal_collection_attempts,
                     :renewal_collection_attempts_dispatch_state_check
                   )

    drop constraint(
           :renewal_collection_attempts,
           "renewal_collection_attempts_payment_intent_id_fkey"
         )

    drop constraint(
           :renewal_collection_attempts,
           "renewal_collection_attempts_renewal_attempt_id_fkey"
         )

    drop table(:renewal_collection_attempts)
  end
end
