defmodule Store.Repo.Migrations.Phase05Uniqueness do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webhook_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :provider, :text, null: false
      add :idempotency_key, :text, null: false
      add :payload_sha256, :text

      add :received_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:webhook_receipts, [:received_at], name: "webhook_receipts_received_at_index")

    create index(:webhook_receipts, [:provider], name: "webhook_receipts_provider_index")

    create unique_index(:webhook_receipts, [:idempotency_key],
             name: "webhook_receipts_unique_idempotency_key_index"
           )

    alter table(:orders) do
      add :order_ref, :text, null: false
    end

    create index(:orders, [:order_ref], name: "orders_order_ref_index")

    create unique_index(:orders, [:order_ref], name: "orders_unique_order_ref_index")
  end

  def down do
    drop_if_exists unique_index(:orders, [:order_ref], name: "orders_unique_order_ref_index")

    drop_if_exists index(:orders, [:order_ref], name: "orders_order_ref_index")

    alter table(:orders) do
      remove :order_ref
    end

    drop_if_exists unique_index(:webhook_receipts, [:idempotency_key],
                     name: "webhook_receipts_unique_idempotency_key_index"
                   )

    drop_if_exists index(:webhook_receipts, [:provider], name: "webhook_receipts_provider_index")

    drop_if_exists index(:webhook_receipts, [:received_at],
                     name: "webhook_receipts_received_at_index"
                   )

    drop table(:webhook_receipts)
  end
end
