defmodule Store.Repo.Migrations.AddTokenIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:tokens, [:purpose, :subject], name: "tokens_purpose_subject_index")

    create index(:tokens, [:expires_at], name: "tokens_expires_at_index")

    create index(:tokens, [:subject], name: "tokens_subject_index")
  end

  def down do
    drop_if_exists index(:tokens, [:subject], name: "tokens_subject_index")

    drop_if_exists index(:tokens, [:expires_at], name: "tokens_expires_at_index")

    drop_if_exists index(:tokens, [:purpose, :subject], name: "tokens_purpose_subject_index")
  end
end
