defmodule Store.Repo.Migrations.Phase03AdminResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:role_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :user_id, :uuid, null: false
      add :role, :text, null: false
      add :assigned_by, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:role_assignments, [:role], name: "role_assignments_role_index")

    create unique_index(:role_assignments, [:user_id, :role],
             name: "role_assignments_unique_user_role_index"
           )

    create table(:audit_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :actor_id, :uuid
      add :action, :text, null: false
      add :resource, :text, null: false
      add :record_id, :uuid
      add :request_id, :text
      add :meta, :map, null: false, default: %{}
      add :payload_sha256, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:audit_logs, [:request_id], name: "audit_logs_request_id_index")

    create index(:audit_logs, [:resource], name: "audit_logs_resource_index")

    create index(:audit_logs, [:action], name: "audit_logs_action_index")

    create index(:audit_logs, [:actor_id], name: "audit_logs_actor_id_index")

    create index(:audit_logs, [:inserted_at], name: "audit_logs_inserted_at_index")
  end

  def down do
    drop_if_exists index(:audit_logs, [:inserted_at], name: "audit_logs_inserted_at_index")

    drop_if_exists index(:audit_logs, [:actor_id], name: "audit_logs_actor_id_index")

    drop_if_exists index(:audit_logs, [:action], name: "audit_logs_action_index")

    drop_if_exists index(:audit_logs, [:resource], name: "audit_logs_resource_index")

    drop_if_exists index(:audit_logs, [:request_id], name: "audit_logs_request_id_index")

    drop table(:audit_logs)

    drop_if_exists unique_index(:role_assignments, [:user_id, :role],
                     name: "role_assignments_unique_user_role_index"
                   )

    drop_if_exists index(:role_assignments, [:role], name: "role_assignments_role_index")

    drop table(:role_assignments)
  end
end
