defmodule Store.Repo.Migrations.S0TaskRenewalGenerationExactKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM inventory_reservations
        WHERE state = 'active'
        GROUP BY order_id, variant_id
        HAVING COUNT(*) > 1
      ) THEN
        RAISE EXCEPTION
          'cannot enable active-only inventory reservation uniqueness: duplicate active order/variant pairs exist';
      END IF;
    END
    $$;
    """)

    create index(:inventory_reservations, [:order_id, :variant_id],
             name: "inventory_reservations_unique_active_order_variant_index",
             unique: true,
             where: "state = 'active'"
           )

    drop_if_exists unique_index(:inventory_reservations, [:order_id, :variant_id],
                     name: "inventory_reservations_unique_order_variant_index"
                   )
  end

  def down do
    raise Ecto.MigrationError,
      message:
        "cannot restore global order/variant uniqueness without deleting valid terminal reservation history"
  end
end
