defmodule Store.Repo.Migrations.Phase06PolicyPolicies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:orders) do
      add :user_id, :uuid
    end

    create index(:orders, [:user_id], name: "orders_user_id_index")
  end

  def down do
    drop_if_exists index(:orders, [:user_id], name: "orders_user_id_index")

    alter table(:orders) do
      remove :user_id
    end
  end
end
