defmodule Store.Repo.Migrations.Phase06PolicyMatrix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:site_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :key, :text, null: false
      add :value, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:site_settings, [:key], name: "site_settings_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:site_settings, [:key], name: "site_settings_unique_key_index")

    drop table(:site_settings)
  end
end
