defmodule Store.Repo.Migrations.SyncCodegenBaseline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:products, [:status, :published_at], name: "products_status_published_at_index")

    alter table(:webhook_receipts) do
      add :evidence_purged_at, :utc_datetime_usec
    end

    create index(:webhook_receipts, [:evidence_purged_at],
             name: "webhook_receipts_evidence_purged_at_index"
           )

    alter table(:orders) do
      add :provider_setup_started_at, :utc_datetime_usec
    end

    create index(:orders, [:state, :inserted_at, :id], name: "orders_state_inserted_at_id_index")

    create index(:orders, [:user_id, :inserted_at, :id],
             name: "orders_user_id_inserted_at_id_index"
           )

    create index(:orders, [:state, :provider_setup_started_at],
             name: "orders_state_provider_setup_started_at_index"
           )

    alter table(:email_outboxes) do
      modify :order_id, :uuid, null: true

      add :subscription_id,
          references(:subscriptions,
            column: :id,
            name: "email_outboxes_subscription_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:email_outboxes, [:subscription_id],
             name: "email_outboxes_subscription_id_index"
           )

    create index(:email_outboxes, [:template_kind, :inserted_at, :id],
             name: "email_outboxes_template_kind_inserted_at_id_index"
           )

    create index(:email_outboxes, [:state, :inserted_at, :id],
             name: "email_outboxes_state_inserted_at_id_index"
           )

    alter table(:payment_intents) do
      add :purpose, :text, null: false, default: "order_checkout"
      add :subscription_id, :uuid
      add :provider_customer_ref, :text
      add :provider_payment_method_ref, :text
    end

    create index(:payment_intents, [:provider, :provider_session_id],
             name: "payment_intents_unique_provider_session_id_index",
             unique: true,
             where: "provider_session_id IS NOT NULL"
           )

    create index(:payment_intents, [:provider, :provider_payment_id],
             name: "payment_intents_unique_provider_payment_id_index",
             unique: true,
             where: "provider_payment_id IS NOT NULL"
           )

    create index(:payment_intents, [:provider_payment_method_ref],
             name: "payment_intents_provider_payment_method_ref_index"
           )

    create index(:payment_intents, [:provider_customer_ref],
             name: "payment_intents_provider_customer_ref_index"
           )

    create index(:payment_intents, [:subscription_id],
             name: "payment_intents_subscription_id_index"
           )

    create index(:payment_intents, [:purpose], name: "payment_intents_purpose_index")

    alter table(:subscriptions) do
      add :quantity, :bigint, null: false, default: 1
      add :renewal_amount_minor, :bigint, null: false
      add :renewal_currency, :text, null: false
      add :membership_key, :text
      add :pending_renewal_amount_minor, :bigint
      add :pending_renewal_currency, :text
      add :change_effective_at, :utc_datetime_usec
      add :dunning_attempt_count, :bigint, null: false, default: 0
      add :next_retry_at, :utc_datetime_usec
      add :retry_suppressed_at, :utc_datetime_usec

      add :variant_id,
          references(:variants,
            column: :id,
            name: "subscriptions_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :pending_subscription_plan_id,
          references(:subscription_plans,
            column: :id,
            name: "subscriptions_pending_subscription_plan_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :pending_variant_id,
          references(:variants,
            column: :id,
            name: "subscriptions_pending_variant_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:subscriptions, [:user_id, :membership_key],
             name: "subscriptions_user_membership_key_index"
           )

    create index(:subscriptions, [:pending_variant_id],
             name: "subscriptions_pending_variant_id_index"
           )

    create index(:subscriptions, [:pending_subscription_plan_id],
             name: "subscriptions_pending_plan_id_index"
           )

    create index(:subscriptions, [:variant_id], name: "subscriptions_variant_id_index")

    create index(:subscriptions, [:status, :next_retry_at],
             name: "subscriptions_status_next_retry_at_index"
           )

    create table(:tool_lead_submissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tool_slug, :text, null: false
      add :name, :text, null: false
      add :email, :text, null: false
      add :phone, :text
      add :consent_contact, :boolean, null: false, default: false
      add :consent_store_data, :boolean, null: false, default: false
      add :score, :bigint, null: false
      add :category, :text, null: false
      add :answers, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:tool_lead_submissions, [:inserted_at],
             name: "tool_lead_submissions_inserted_at_index"
           )

    create index(:tool_lead_submissions, [:email], name: "tool_lead_submissions_email_index")

    create index(:tool_lead_submissions, [:tool_slug],
             name: "tool_lead_submissions_tool_slug_index"
           )

    create index(:fulfillment_orders, [:state, :inserted_at, :id],
             name: "fulfillment_orders_state_inserted_at_id_index"
           )
  end

  def down do
    drop_if_exists index(:fulfillment_orders, [:state, :inserted_at, :id],
                     name: "fulfillment_orders_state_inserted_at_id_index"
                   )

    drop_if_exists index(:tool_lead_submissions, [:tool_slug],
                     name: "tool_lead_submissions_tool_slug_index"
                   )

    drop_if_exists index(:tool_lead_submissions, [:email],
                     name: "tool_lead_submissions_email_index"
                   )

    drop_if_exists index(:tool_lead_submissions, [:inserted_at],
                     name: "tool_lead_submissions_inserted_at_index"
                   )

    drop table(:tool_lead_submissions)

    drop constraint(:subscriptions, "subscriptions_variant_id_fkey")

    drop constraint(:subscriptions, "subscriptions_pending_subscription_plan_id_fkey")

    drop constraint(:subscriptions, "subscriptions_pending_variant_id_fkey")

    drop_if_exists index(:subscriptions, [:status, :next_retry_at],
                     name: "subscriptions_status_next_retry_at_index"
                   )

    drop_if_exists index(:subscriptions, [:variant_id], name: "subscriptions_variant_id_index")

    drop_if_exists index(:subscriptions, [:pending_subscription_plan_id],
                     name: "subscriptions_pending_plan_id_index"
                   )

    drop_if_exists index(:subscriptions, [:pending_variant_id],
                     name: "subscriptions_pending_variant_id_index"
                   )

    drop_if_exists index(:subscriptions, [:user_id, :membership_key],
                     name: "subscriptions_user_membership_key_index"
                   )

    alter table(:subscriptions) do
      remove :pending_variant_id
      remove :pending_subscription_plan_id
      remove :variant_id
      remove :retry_suppressed_at
      remove :next_retry_at
      remove :dunning_attempt_count
      remove :change_effective_at
      remove :pending_renewal_currency
      remove :pending_renewal_amount_minor
      remove :membership_key
      remove :renewal_currency
      remove :renewal_amount_minor
      remove :quantity
    end

    drop_if_exists index(:payment_intents, [:purpose], name: "payment_intents_purpose_index")

    drop_if_exists index(:payment_intents, [:subscription_id],
                     name: "payment_intents_subscription_id_index"
                   )

    drop_if_exists index(:payment_intents, [:provider_customer_ref],
                     name: "payment_intents_provider_customer_ref_index"
                   )

    drop_if_exists index(:payment_intents, [:provider_payment_method_ref],
                     name: "payment_intents_provider_payment_method_ref_index"
                   )

    drop_if_exists index(:payment_intents, [:provider, :provider_payment_id],
                     name: "payment_intents_unique_provider_payment_id_index"
                   )

    drop_if_exists index(:payment_intents, [:provider, :provider_session_id],
                     name: "payment_intents_unique_provider_session_id_index"
                   )

    alter table(:payment_intents) do
      remove :provider_payment_method_ref
      remove :provider_customer_ref
      remove :subscription_id
      remove :purpose
    end

    drop constraint(:email_outboxes, "email_outboxes_subscription_id_fkey")

    drop_if_exists index(:email_outboxes, [:state, :inserted_at, :id],
                     name: "email_outboxes_state_inserted_at_id_index"
                   )

    drop_if_exists index(:email_outboxes, [:template_kind, :inserted_at, :id],
                     name: "email_outboxes_template_kind_inserted_at_id_index"
                   )

    drop_if_exists index(:email_outboxes, [:subscription_id],
                     name: "email_outboxes_subscription_id_index"
                   )

    alter table(:email_outboxes) do
      remove :subscription_id
      modify :order_id, :uuid, null: false
    end

    drop_if_exists index(:orders, [:state, :provider_setup_started_at],
                     name: "orders_state_provider_setup_started_at_index"
                   )

    drop_if_exists index(:orders, [:user_id, :inserted_at, :id],
                     name: "orders_user_id_inserted_at_id_index"
                   )

    drop_if_exists index(:orders, [:state, :inserted_at, :id],
                     name: "orders_state_inserted_at_id_index"
                   )

    alter table(:orders) do
      remove :provider_setup_started_at
    end

    drop_if_exists index(:webhook_receipts, [:evidence_purged_at],
                     name: "webhook_receipts_evidence_purged_at_index"
                   )

    alter table(:webhook_receipts) do
      remove :evidence_purged_at
    end

    drop_if_exists index(:products, [:status, :published_at],
                     name: "products_status_published_at_index"
                   )
  end
end
