defmodule Store.Support.Errors.ErrorCodes do
  @moduledoc """
  Stable, registry-backed error codes.
  """

  @codes [
    "UNAUTHORIZED",
    "FORBIDDEN",
    "NOT_FOUND",
    "STEP_UP_REQUIRED",
    "INVALID_STATE_TRANSITION",
    "STALE_RECORD",
    "WEBHOOK_DUPLICATE",
    "VALIDATION_ERROR",
    "INTERNAL_ERROR",
    "INVALID_COUPON",
    "CHECKOUT_DUPLICATE",
    "PAYMENT_INTENT_DUPLICATE",
    "PAYMENT_ALREADY_SUCCEEDED",
    "OUT_OF_STOCK",
    "RESERVATION_CONFLICT",
    "REFUND_NOT_ALLOWED",
    "REFUND_EXCEEDS_REFUNDABLE",
    "REFUND_DUPLICATE",
    "IDEMPOTENCY_KEY_REUSE_MISMATCH",
    "CURRENCY_MISMATCH",
    "PAYMENT_PROVIDER_REFUND_FAILED",
    "INVALID_ADDRESS",
    "SHIPPING_RATE_NOT_FOUND",
    "TAX_RATE_NOT_FOUND",
    "ORDER_NOT_FOUND",
    "ORDER_NOT_OWNED",
    "PAYMENT_PROVIDER_VERIFICATION_FAILED",
    "PAYMENT_SIGNATURE_MISSING",
    "PAYMENT_SIGNATURE_INVALID",
    "PAYMENT_PAYLOAD_INVALID",
    "PAYMENT_EVENT_DUPLICATE",
    "PAYMENT_PROVIDER_DOWN",
    "PAYMENT_PROVIDER_TIMEOUT",
    "PAYMENT_PROCESSING_FAILED",
    "PAYMENT_EVENT_UNVERIFIED",
    "PAYMENT_PROVIDER_DISABLED",
    "PAYMENT_FAILED",
    "PAYMENT_METHOD_REQUIRED",
    "PAYMENT_PROVIDER_SELECTION_REQUIRED",
    "PAYMENT_PROVIDER_UNSUPPORTED",
    "RATE_LIMITED",
    "SLUG_TAKEN",
    "SKU_TAKEN",
    "VARIANT_IN_USE",
    "DIGITAL_GRANT_NOT_FOUND",
    "DIGITAL_GRANT_DENIED",
    "DIGITAL_GRANT_EXPIRED",
    "DIGITAL_GRANT_REVOKED",
    "DIGITAL_REDIRECT_UNSAFE",
    "DIGITAL_DOWNLOAD_RATE_LIMITED",
    "SUBSCRIPTION_NOT_FOUND",
    "SUBSCRIPTION_DUPLICATE",
    "SUBSCRIPTION_RENEWAL_DUPLICATE",
    "SUBSCRIPTION_MISSING_BILLING_REFERENCE",
    "SUBSCRIPTION_PLAN_NOT_FOUND",
    "SUBSCRIPTION_PROVIDER_SELECTION_REQUIRED",
    "SUBSCRIPTION_PROVIDER_UNSUPPORTED",
    "SUBSCRIPTION_PROVIDER_MODE_DISABLED",
    "SUBSCRIPTION_BILLING_MODE_UNSUPPORTED",
    "SUBSCRIPTION_PURCHASE_DISABLED",
    "VARIANT_PLAN_UNAVAILABLE",
    "SHIPPING_PROVIDER_DOWN",
    "SHIPPING_UNAVAILABLE",
    "SHIPPING_PROFILE_MISSING",
    "SHIPPING_COST_SURGE",
    "PAYMENT_METHOD_UPDATE_UNSUPPORTED",
    "PAYMENT_AUTHENTICATION_REQUIRED",
    "ENTITLEMENT_NOT_FOUND",
    "ENTITLEMENT_DUPLICATE"
  ]

  @compile {:inline, exists?: 1}
  @codes_map Map.new(@codes, &{&1, true})

  if length(@codes) != map_size(@codes_map) do
    raise "duplicate error codes in Store.Support.Errors.ErrorCodes"
  end

  @spec all() :: [String.t()]
  def all do
    Enum.sort(@codes)
  end

  @spec exists?(String.t()) :: boolean()
  def exists?(code) when is_binary(code) do
    Map.has_key?(@codes_map, code)
  end
end
